### PR TITLE
Updated create-fiwl-app workflow in README

### PR DESCRIPTION
**Pull request by BraydenTW**
You actually do not need to use the `npm i create-fiwl-app -g` for running `npx create-fiwl-app`.

It runs no matter what.

### CODE REVIEW

**Comment by yummyweb** [comment]
Hey Brayden, I understand your point but the thing is, you need to install create-fiwl-app. To do that we run the command `npm i create-fiwl-app -g`. Without installing, we cannot run npx create-fiwl-app. And if you notice, I have written and I quote: "To install the cli run the command below". Here cli is the create-fiwl-app.

**Comment by BraydenTW** [comment]
Sorry @antriksh123 , no you do not. 

Using "npx" will always get the latest version of create-fiwl-app. 

Again, you do not need to install create-fiwl-app to use the npx command. 

Have you tried using npx all by itself? It is really quite simple.

Let me know if you have any other questions.

**Comment by yummyweb** [comment]
Oh ok! Merging this PR then.

**Comment by BraydenTW** [comment]
Sounds good. Thanks!

**Pull request merged**
